# Generated by Django 3.1.14 on 2023-06-27 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20181018_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
